
SPRITESHEET_PATH = "Main_Assets/Spritesheets"

WINDOW_WIDTH, WINDOW_HEIGHT = 960, 540

GRAVITY = 0.6

MC_SPEED = 4
ANIMATIONSPEED_MC_DEFAULT = 0.25
ANIMATIONSPEED_MC_IDLE = 0.1

SPEED_FLYINGEYE = 2

ANIMATIONSPEED_EYE = 0.2

ANIMATIONSPEED_ATTACK_EYE = 0.75